[build]
builder = "DOCKERFILE"
dockerfilePath = "apps/web/Dockerfile"

[deploy]
startCommand = "sh -c 'node_modules/.bin/next start -H ${HOSTNAME:-0.0.0.0} -p ${PORT:-3000}'"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
